
CREATE TABLE products (
Id INT PRIMARY KEY ,
name VARCHAR(50) UNIQUE NOT NULL,
desc VARCHAR(100) UNIQUE NOT NULL,
SKU VARCHAR(100) NOT NULL,
Category_Id INT,
Inventory_Id INT,
price INT,
discout_Id INT,
Created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
Modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
Deleted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP

);
CREATE TABLE Posts (
PostID INT PRIMARY KEY,
UserID INT,
Title VARCHAR(100) NOT NULL,
Content TEXT NOT NULL,
CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE CASCADE
);